Airbnb listing details page by Yevhen Sahach
mate-academy/layout_listing-details-airbnb pull request #2
Opened 2019-08-10 18:31 UTC by yevhen-sahach

* [DEMO LINK](https://yevhen-sahach.github.io/layout_listing-details-airbnb/)

2019-08-21 07:03 UTC, danheim requested changes

2019-08-21 07:03 UTC, danheim commented on src/index.html
> +            <a href="#" class="lodging__contact-host">Contact host</a>
Кнопка

2019-08-21 07:03 UTC, danheim commented on src/index.html
> +              <p class="review__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
Перенос текста

2019-08-21 07:03 UTC, danheim commented on src/index.html
> +                <span class="review__time">September 2016</span>
```suggestion
                <span class="review__date">September 2016</span>
```

2019-08-21 07:03 UTC, danheim commented on src/index.html
> +              <a href="#" class="">
зачем пустой класс?

2019-08-21 07:03 UTC, danheim commented on src/index.html
> +          <li class="footer__list-item">Help</li>
Последние три должны быть ссылками

2019-08-21 07:03 UTC, danheim commented on src/index.html
> +          <li class="footer__list-item">Guidebooks</li>
Последние три должны быть ссылками

2019-08-21 07:03 UTC, danheim commented on src/index.html
> +          <li class="footer__list-item">Community</li>
Последние три должны быть ссылками

2019-08-21 07:03 UTC, danheim commented on src/index.html
>      <script type="text/javascript" src="scripts/main.js"></script>
Удаляем неиспользуемый код

2019-08-31 12:52 UTC, yevhen-sahach commented on src/index.html
> +            <a href="#" class="lodging__contact-host">Contact host</a>
Почему ты так считаешь? на макете это просто текст без каких либо бордеров

2019-08-31 12:55 UTC, yevhen-sahach commented on src/index.html
> +        <a href="#" class="profile-photo">
почему кнопка? мне кажется что задумка тут задумка с дропдауном, просто я пока что не умею такое реализовывать поэтому пока что ссылка

2019-09-03 07:52 UTC, irenhh requested changes
1. сделай ховер эффект на кнопках одинакового стиля
2. Show all amenities - это ссылка
3. все ховеры ссылок лучше сделать одинаковыми
4. шрифт на форме маловат + кнопки

2019-09-03 07:52 UTC, irenhh commented on src/index.html
> +              <p class="review__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
почему нет переноса?

2019-09-03 07:52 UTC, irenhh commented on src/index.html
> +          <li class="footer__list-item"><a href="" class="footer__list-item--link">About</a></li>
вложенные тэги обязательно переносить на новую строку

2019-09-10 14:57 UTC, irenhh requested changes
- на второй кнопке нет курсора нужного
- на ссылке contact host нету ховера

2019-09-11 07:53 UTC, irenhh approved these changes

2023-01-14 15:21 UTC, closed without merging